### ISSUE TITLE
Change ChildAccount from key based approach to AuthAccount capability usage 

### ISSUE THREAD

**Issue by alilloig** [onflow/sc-eng-gaming#31]
### Issue To Be Solved
The child account code has been created with the key based approach in mind. When the AuthAccount capability is live, we should change that code to use it.

**Comment by sisyphusSmiling** [comment]
Quick update: resolution here depends on the definition of done. Completion tied up in the changes we're making to the child account demo since we're figuring out implementation details as we go. We're shooting for an end-to-end demo late next week/early following week, but child account implementations won't be formally complete until the Flip for a standard child account management resource is introduced & accepted.

For the purpose of this issue, we'll consider this closed when the PR containing contract defining `ChildAccountManager` definition is merged ([sisyphusSmiling/child-account-auth-acct-cap branch](https://github.com/onflow/sc-eng-gaming/tree/sisyphusSmiling/child-account-auth-acct-cap)). Introducing this PR is dependent on #33, but we hope to get the PR merged in the next two weeks.
